services:

  general:
    build: ./
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
      - /app/.venv
      - ./01-agentic-rag/ingest.py:/app/ingest.py:ro
    env_file:
      - .env
    restart: unless-stopped

  module-01:
    build: ./01-agentic-rag
    ports:
      - "8889:8888"
    volumes:
      - ./01-agentic-rag:/app
      - /app/.venv
    env_file:
      - .env
    restart: unless-stopped

  module-02:
    build: ./02-vector-search
    ports:
      - "8890:8888"
    volumes:
      - ./02-vector-search:/app
      - /app/.venv
    env_file:
      - .env
    restart: unless-stopped

  module-02-homework:
    build: ./02-vector-search/02-homework
    ports:
      - "8891:8888"
    volumes:
      - ./02-vector-search/02-homework:/app
      - /app/.venv
      - ./02-vector-search/02-homework/ingest.py:/app/ingest.py:ro
      - ./01-agentic-rag/rag_helper.py:/app/rag_helper.py:ro
      - ./02-vector-search/02-homework/embed:/app/embed:ro

    env_file:
      - .env
    restart: unless-stopped

  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: faq
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgvector_data:
